<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Rama-PC" name="com.AppICE_ModuleNamesValidation.TC_0002_verifyTheTexts" tests="1" failures="0" timestamp="21 Sep 2016 11:05:59 GMT" time="22.523" errors="1">
  <testcase name="verifyTheTexts" time="22.523" classname="com.AppICE_ModuleNamesValidation.TC_0002_verifyTheTexts">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;... New ...&gt; but was:&lt;... New ...&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<... New ...> but was:<... New ...>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at com.AppICE_pageObject_Classes.AppICE_HomePage.verifyTexts(AppICE_HomePage.java:108)
	at com.AppICE_ModuleNamesValidation.TC_0002_verifyTheTexts.verifyTheTexts(TC_0002_verifyTheTexts.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- verifyTheTexts -->
</testsuite> <!-- com.AppICE_ModuleNamesValidation.TC_0002_verifyTheTexts -->
